apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "app.name" . }}-config
data:
  ENV: {{ .Values.env.ENV | quote }}
  SERVICE_NAME: {{ .Values.env.SERVICE_NAME | quote }}
  SERVICE_VERSION: {{ .Values.env.SERVICE_VERSION | quote }}
  OTLP_ENDPOINT: {{ .Values.env.OTLP_ENDPOINT | quote }}
  HTTP_ADDR: {{ .Values.http.addr | quote }}
  GRPC_PORT: {{ .Values.grpc.port | quote }}
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.name | quote }}
  DB_USER: {{ .Values.db.user | quote }}
  REDIS_ADDR: {{ .Values.redis.addr | quote }}
  REDIS_DB: {{ .Values.redis.db | quote }}
  REDIS_USER: {{ .Values.redis.user | quote }}
  SCHEDULER_INTERVAL: {{ .Values.scheduler.interval | quote }}
  SCHEDULER_SERVERS: {{ .Values.scheduler.servers | quote }}
  SCHEDULER_TOPIC: {{ .Values.scheduler.topic | quote }}
  SCHEDULER_CLIENT_ID: {{ .Values.scheduler.client_id | quote }}
  JWT_ACCESS_TOKEN_LIFE_TIME: {{ .Values.jwt.access_token_life_time | quote }}
  JWT_PUBLIC_KEY_PATH: {{ .Values.jwt.public_key_path | quote}}
  JWT_PRIVATE_KEY_PATH: {{ .Values.jwt.private_key_path | quote}}
