apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/app: {{ include "app.name" . }}
    app.kubernetes.io/version: {{ include "app.version" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ include "app.name" . }}
      app.kubernetes.io/version: {{ include "app.version" . }}
  replicas: {{ .Values.replicaCount }}

  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ include "app.name" . }}
        app.kubernetes.io/version: {{ include "app.version" . }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ include "app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.http.port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.grpc.port }}
              protocol: TCP
          volumeMounts:
            - name: jwt-secrets
              mountPath: /private.pem
              subPath: private.pem
              readOnly: true
            - name: jwt-secrets
              mountPath: /public.pem
              subPath: public.pem
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: {{ include "app.name" . }}-config 
            - secretRef:
                name: {{ include "app.name" . }}-secrets
    volumes:
      - name: jwt-secrets
        secret:
          secretName: {{ "jwt-keys" }}
          items:
              - key: private.pem
                path: private.pem
                mode: 0444
              - key: public.pem
                path: public.pem
                mode: 0444
