apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/app: {{ include "app.name" . }}
    app.kubernetes.io/version: {{ include "app.version" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/app: {{ include "app.name" . }}
    app.kubernetes.io/version: {{ include "app.version" . }}
  ports:
    - name: http
      port: {{ .Values.http.port }}
      targetPort: {{ .Values.http.port }}
    - name: grpc
      port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.port }}
